version_major = 0
version_minor = 1

[rb_Register_Block678]
autogen_codename = "false"
codename = "Register_Block678"
description = ""
name = "Register Block 1"
size = 1024

[rb_Register_Block678.registers]

[rb_Register_Block678.registers.0_New_Register_0]
autogen_codename = "true"
bit_len = 8
codename = "New_Register_0"
description = """
wawaweewoo descrtiption


text gere\
"""
name = "New Register 0"
offset = 0

[rb_Register_Block678.registers.1_New_Register_1]
autogen_codename = "true"
bit_len = 8
codename = "New_Register_1"
description = ""
name = "New Register 1"
offset = 1

[rb_Register_Block678.registers.1_New_Register_1.bit_fields]

[rb_Register_Block678.registers.1_New_Register_1.bit_fields.0_idxbf]
autogen_codename = "true"
codename = "idxbf"
description = ""
high_idx = 0
low_idx = 0
name = "idx)bf"

[rb_Register_Block678.registers.1_New_Register_1.bit_fields.1_BitField_1]
autogen_codename = "true"
codename = "BitField_1"
description = ""
high_idx = 1
low_idx = 1
name = "BitField 1"

[rb_Register_Block678.registers.1_New_Register_1.bit_fields.2_BitField_23]
autogen_codename = "true"
codename = "BitField_23"
description = ""
high_idx = 3
low_idx = 2
name = "BitField 23"


[rb_Register_Block678.registers.2_New_Register_2846]
autogen_codename = "false"
bit_len = 7
codename = "New_Register_2846"
description = ""
name = "New Register 2"
offset = 2

[rb_Register_Block678.registers.3_New_Register_3]
autogen_codename = "true"
bit_len = 16
codename = "New_Register_3"
description = ""
name = "New Register 3"
offset = 3

[rb_Register_Block678.registers.4_New_Register_4]
autogen_codename = "true"
bit_len = 12
codename = "New_Register_4"
description = ""
name = "New Register 4"
offset = 4

[rb_Register_Block_0]
autogen_codename = "true"
codename = "Register_Block_0"
description = ""
name = "Register Block 0"
size = 1024

[rb_Register_Block_0.registers]

[rb_Register_Block_0.registers.0__000000]
autogen_codename = "true"
bit_len = 800
codename = "_000000"
description = ""
name = "000000"
offset = 0

[rb_Register_Block_0.registers.2_New_Register_2]
autogen_codename = "true"
bit_len = 8
codename = "New_Register_2"
description = ""
name = "New Register 2"
offset = 2

[rb_Register_Block_0.registers.6_New_Register_1]
autogen_codename = "true"
bit_len = 8
codename = "New_Register_1"
description = ""
name = "New Register 1"
offset = 6



